name: build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest  # 使用 Windows 最新版本运行器

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: '4.8'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build
