name: build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest  # 使用 Windows 最新版本运行器

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Restore dependencies
      run: nuget restore

    - name: Build the project
      run: msbuild ass-os.sln /p:Configuration=Release /p:Platform="Any CPU"
